# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sr7e0I3BJ_EqgfkywmEn4rXVuRAwQwn6
"""

!pip install -q -U google-generativeai

import asyncio
from fastapi import FastAPI
import nest_asyncio
import uvicorn

app = FastAPI()

@app.get("/")
def home():
    return {"message": "AI Controller Running"}

@app.get("/predict")
def predict(value: float):
    result = value * 2  # yahan apna AI logic/model lagao
    return {"output": result}

nest_asyncio.apply()

# Configure Uvicorn server
config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
server = uvicorn.Server(config)

# Run the server as a background task
asyncio.create_task(server.serve())

# Print a message indicating the server is starting
print("FastAPI server started on http://0.0.0.0:8000")

from pyngrok import ngrok
from google.colab import userdata

# Get ngrok authtoken from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN') # Use the secret's name, not its value

# Authenticate ngrok
if NGROK_AUTH_TOKEN:
    ngrok.set_auth_token(NGROK_AUTH_TOKEN) # Use the variable, which is a string
else:
    print("Error: NGROK_AUTH_TOKEN not found in Colab secrets. Please add it.")

public_url = ngrok.connect(8000)
print(public_url)

import google.generativeai as genai
from google.colab import userdata

# Get the API key securely from Colab's user data secretshttp://localhost:8000/
api_key = userdata.get('google-api-key')

# Verify the API key
print(f"API Key retrieved: {api_key}")

# Configure the genai library with the API key
genai.configure(api_key=api_key)

model = genai.GenerativeModel('gemini-2.5-flash')

from google.colab import userdata
userdata.get('google-api-key')

from google.colab import userdata
userdata.get('google-api-key')

# Create a chat session that supports 'Function Calling'
chat = model.start_chat(enable_automatic_function_calling=True)

prompt = "Check the system temperature. If it is over 80 degrees, turn on active cooling to 100%."

response = chat.send_message(prompt)

print(f"AI Decision: {response.text}")

"""```markdown
To force the AI to use the available functions, you can specify the `tool_config` with `mode='ANY'` when starting the chat session. This ensures that if the AI can interpret your prompt as a function call, it will execute it.
```
"""

import google.generativeai as genai

# Define the functions that the AI can call
def check_system_temperature():
    """Checks the current system temperature."""
    # In a real scenario, this would interact with system sensors
    print("Checking system temperature...")
    return {"temperature": 75, "unit": "Fahrenheit"}

def turn_on_active_cooling(percentage: int):
    """Turns on active cooling to a specified percentage.

    Args:
        percentage (int): The percentage to set the active cooling to (0-100).
    """
    print(f"Turning on active cooling to {percentage}%...")
    # In a real scenario, this would interact with system cooling hardware
    return {"status": "Cooling activated", "percentage": percentage}

# Pass the Python functions directly as tools
model_tools = [check_system_temperature, turn_on_active_cooling]

# Create a dictionary to map function names to their callable Python implementations
callable_tools = {
    "check_system_temperature": check_system_temperature,
    "turn_on_active_cooling": turn_on_active_cooling,
}

# Create a chat session
forced_chat = model.start_chat(
    enable_automatic_function_calling=True
)

prompt_force = "Check the system temperature. If it is over 80 degrees, turn on active cooling to 100%."

response_forced = forced_chat.send_message(
    prompt_force,
    tools=model_tools, # Pass the list of Python functions here
    tool_config={'function_calling_config': {'mode': 'ANY'}} # tool_config moved to send_message
)

# Correctly check for a function call in the response's content parts
if response_forced.candidates and response_forced.candidates[0].content.parts:
    first_part = response_forced.candidates[0].content.parts[0]
    if hasattr(first_part, 'function_call') and first_part.function_call:
        function_name = first_part.function_call.name
        function_args = first_part.function_call.args
        print(f"AI wants to call function: {function_name} with arguments: {function_args}")

        # Execute the function using the callable_tools dictionary
        if function_name in callable_tools:
            result = callable_tools[function_name](**function_args)
            print(f"Function execution result: {result}")
        else:
            print(f"Error: Function {function_name} not found in callable_tools.")
    else:
        # If no function_call in the first part, then it must be text
        print(f"AI Decision with forced tool_config: {response_forced.text}")
else:
    # Fallback if no candidates or no parts (e.g., empty response), print text if possible
    print(f"AI Decision with forced tool_config: {response_forced.text}")

"""### Persisting Model Configuration

Since the `genai.GenerativeModel` object cannot be directly pickled, you can save its configuration parameters (like the model name) to a file and then use those parameters to re-instantiate the model when needed.
"""

# Define the model name
model_name = 'gemini-2.5-flash'

# Save the model name to a text file
with open('model_config.txt', 'w') as f:
    f.write(model_name)

print(f"Model configuration (name: {model_name}) saved to model_config.txt")

"""### Loading Model Configuration and Re-instantiating the Model

Now, you can load the model name from the file and create a new `GenerativeModel` instance.
"""